# docker-sync for Mac and Windows docker performance https://docker-sync.readthedocs.io/

version: '3'

services:
  webserver:
    volumes:
      - docker-sync:/var/www/html:cached

volumes:
  docker-sync:
    external:
     name: "${COMPOSE_PROJECT_NAME}-sync"